-- 재물운 앱 질문 100개 + 선택지 400개 시드 데이터
BEGIN TRANSACTION;
DELETE FROM choices;
DELETE FROM questions;
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (1, 'money', 'daily', '💰', '오늘 아침 지갑이나 계좌를 떠올렸을 때 가장 먼저 든 생각은?', '평소와 가장 가까운 반응을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (1, 1, '오늘 쓸 돈부터 계산한다', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (2, 1, '별생각 없이 넘어간다', 4, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (3, 1, '좋은 흐름이 올 것 같다고 느낀다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (4, 1, '지출 걱정이 먼저 든다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (2, 'money', 'daily', '🪙', '예상치 못한 5만원이 생기면 가장 먼저 무엇을 하나요?', '직감적으로 선택해 주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (5, 2, '바로 저축한다', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (6, 2, '소액 투자에 넣어본다', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (7, 2, '먹고 싶은 것을 산다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (8, 2, '가족이나 친구를 위해 쓴다', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (3, 'money', 'luck', '🍀', '오늘 운이 좋다고 느끼는 순간이 있다면 어떤 때인가요?', '가장 공감되는 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (9, 3, '할인이나 쿠폰을 발견했을 때', 7, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (10, 3, '뜻밖의 연락이나 제안을 받을 때', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (11, 3, '지출 없이 하루가 지나갈 때', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (12, 3, '그런 느낌은 별로 없다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (4, 'money', 'daily', '☕', '카페에서 음료를 살 때 평소 패턴은 어떤가요?', '일상 습관에 가장 가까운 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (13, 4, '가격부터 본다', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (14, 4, '기분 따라 주문한다', 4, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (15, 4, '쿠폰이나 적립 여부를 먼저 본다', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (16, 4, '함께 있는 사람 분위기를 따른다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (5, 'money', 'luck', '🎁', '선물이나 보너스를 받으면 어떤 감정이 가장 먼저 드나요?', '가장 솔직한 답을 선택해 주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (17, 5, '기회가 왔다고 느낀다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (18, 5, '아껴 써야겠다고 생각한다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (19, 5, '바로 쓰고 싶다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (20, 5, '다음에도 이런 일이 생길까 생각한다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (6, 'money', 'money_habit', '📱', '결제 알림이 뜰 때 당신의 반응은?', '평소와 가장 비슷한 반응을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (21, 6, '지출 내역을 바로 확인한다', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (22, 6, '대충 보고 넘긴다', 4, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (23, 6, '예산 안인지 계산한다', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (24, 6, '괜히 불안해진다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (7, 'money', 'money_habit', '🏦', '월급날 또는 입금일에 가장 먼저 하는 행동은?', '가장 자주 하는 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (25, 7, '저축/투자부터 분리한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (26, 7, '이번 달 쓸돈을 계산한다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (27, 7, '사고 싶던 것을 찾아본다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (28, 7, '일단 기분 좋게 쉬고 본다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (8, 'money', 'luck', '🌈', '길을 걷다가 우연히 동전을 보면 어떻게 하나요?', '재미로 가장 가까운 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (29, 8, '주워서 보관한다', 7, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (30, 8, '행운의 신호라고 생각한다', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (31, 8, '그냥 지나친다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (32, 8, '사진 찍어 두고 싶다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (9, 'money', 'daily', '🧾', '가계부나 소비 기록을 얼마나 자주 확인하나요?', '평소 습관에 맞게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (33, 9, '거의 매일 본다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (34, 9, '주 1~2회 본다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (35, 9, '생각날 때만 본다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (36, 9, '거의 보지 않는다', 2, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (10, 'money', 'luck', '🎯', '오늘 돈과 관련해 가장 기대되는 일은 무엇인가요?', '직관적으로 선택해 주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (37, 10, '생각보다 지출이 적은 것', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (38, 10, '작은 수입이 생기는 것', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (39, 10, '좋은 할인 기회를 찾는 것', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (40, 10, '딱히 기대는 없다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (11, 'money', 'daily', '🛒', '마트나 편의점에서 장을 볼 때 가장 먼저 하는 일은?', '평소 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (41, 11, '가격표를 비교한다', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (42, 11, '필요한 것만 빠르게 산다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (43, 11, '행사 코너부터 본다', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (44, 11, '눈에 띄는 걸 담는다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (12, 'money', 'money_habit', '📅', '월말이 다가오면 어떤 마음이 드나요?', '평소 상태와 가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (45, 12, '예산 마무리를 점검한다', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (46, 12, '이번 달도 잘 버텼다고 느낀다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (47, 12, '돈이 어디 갔는지 궁금하다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (48, 12, '괜히 초조하다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (13, 'money', 'luck', '🔔', '알림이 울렸을 때 가장 기대되는 메시지는?', '가장 공감되는 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (49, 13, '입금 알림', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (50, 13, '할인 쿠폰 알림', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (51, 13, '포인트 적립 알림', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (52, 13, '친구의 밥 약속 연락', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (14, 'money', 'money_habit', '💳', '카드를 여러 장 쓸 때 당신의 방식은?', '가장 자주 하는 방식으로 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (53, 14, '혜택별로 나눠 쓴다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (54, 14, '주로 한 장만 쓴다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (55, 14, '되는 대로 쓴다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (56, 14, '카드보다 현금을 선호한다', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (15, 'money', 'daily', '🌙', '잠들기 전 돈과 관련해 가장 자주 떠올리는 것은?', '솔직한 답을 선택해 주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (57, 15, '내일 쓸 예산', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (58, 15, '더 벌 수 있는 방법', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (59, 15, '오늘 쓴 돈', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (60, 15, '가능하면 생각 안 한다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (16, 'money', 'luck', '🚪', '새로운 기회 제안을 받았을 때 보통 어떤 편인가요?', '재물운과 관련한 태도를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (61, 16, '내용을 꼼꼼히 본 뒤 판단한다', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (62, 16, '좋아 보이면 빠르게 잡는다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (63, 16, '일단 의심부터 든다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (64, 16, '귀찮아서 넘긴다', 2, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (17, 'money', 'money_habit', '🧠', '돈을 잘 모은 사람을 보면 가장 먼저 드는 생각은?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (65, 17, '습관이 중요하구나', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (66, 17, '나도 해볼 수 있겠다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (67, 17, '운도 따라야 한다', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (68, 17, '나는 쉽지 않을 것 같다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (18, 'money', 'daily', '📦', '택배가 도착했을 때 어떤 기분이 드나요?', '평소와 비슷한 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (69, 18, '만족감이 든다', 5, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (70, 18, '필요한 걸 잘 샀다고 느낀다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (71, 18, '돈 쓴 게 잠깐 떠오른다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (72, 18, '다음엔 더 신중해야지 생각한다', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (19, 'money', 'luck', '💡', '갑자기 떠오른 아이디어로 돈을 벌 수 있다면?', '가장 가까운 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (73, 19, '메모하고 구체화한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (74, 19, '가볍게 검색해 본다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (75, 19, '좋지만 실행은 미룬다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (76, 19, '금방 잊어버린다', 2, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (20, 'money', 'money_habit', '🧮', '1만원 이하 소액 지출도 신경 쓰는 편인가요?', '평소 습관에 맞게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (77, 20, '꼼꼼히 본다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (78, 20, '어느 정도만 본다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (79, 20, '큰돈만 신경 쓴다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (80, 20, '잘 모르겠다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (21, 'money', 'daily', '👛', '지갑 안 현금이 거의 없을 때 반응은?', '가장 솔직한 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (81, 21, '바로 채워 넣는다', 7, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (82, 21, '요즘은 카드/간편결제면 충분하다', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (83, 21, '왠지 불안하다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (84, 21, '현금 안 써서 신경 안 쓴다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (22, 'money', 'luck', '🎈', '우연히 좋은 가격을 발견했을 때 당신은?', '가장 가까운 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (85, 22, '필요 여부부터 생각한다', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (86, 22, '이건 행운이라며 산다', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (87, 22, '일단 저장해 둔다', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (88, 22, '관심 없다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (23, 'money', 'money_habit', '🧺', '정기구독 서비스는 어떻게 관리하나요?', '실제 패턴에 가깝게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (89, 23, '정기적으로 정리한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (90, 23, '가끔 한 번씩 확인한다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (91, 23, '결제될 때 알게 된다', 3, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (92, 23, '신경 안 쓰는 편이다', 2, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (24, 'money', 'daily', '🚶', '외출 전에 체크하는 것 중 돈과 가장 관련 있는 것은?', '가장 가까운 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (93, 24, '카드/지갑 챙겼는지', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (94, 24, '쿠폰/포인트 있는지', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (95, 24, '오늘 예산 얼마인지', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (96, 24, '딱히 없다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (25, 'money', 'luck', '🪄', '작은 행운이 이어질 때 당신은 어떻게 하나요?', '가장 비슷한 반응을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (97, 25, '기회를 더 살핀다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (98, 25, '기분 좋게 즐긴다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (99, 25, '우연이라 생각한다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (100, 25, '오히려 불안하다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (26, 'money', 'money_habit', '📈', '소액이라도 투자 경험이 생기면 어떤가요?', '가장 가까운 태도를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (101, 26, '원리를 더 공부한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (102, 26, '작게 계속 해본다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (103, 26, '수익만 확인한다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (104, 26, '불안해서 금방 그만둔다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (27, 'money', 'daily', '🍱', '점심 메뉴를 고를 때 가장 큰 기준은?', '가장 자주 따르는 기준을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (105, 27, '가격', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (106, 27, '만족감', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (107, 27, '가성비', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (108, 27, '오늘 기분', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (28, 'money', 'luck', '📬', '예상보다 좋은 소식이 오면 당신은?', '가장 가까운 반응을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (109, 28, '곧바로 다음 계획을 세운다', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (110, 28, '오늘은 운이 좋다고 느낀다', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (111, 28, '일단 저장해 둔다', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (112, 28, '믿기지 않아 확인부터 한다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (29, 'money', 'money_habit', '🧿', '행운 아이템이나 루틴을 믿는 편인가요?', '재미로 가장 가까운 항목을 선택해 주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (113, 29, '있으면 챙긴다', 7, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (114, 29, '재미로 믿는다', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (115, 29, '기회가 왔을 때만 떠올린다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (116, 29, '전혀 신경 안 쓴다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (30, 'money', 'daily', '📊', '이번 주 돈 흐름을 한 단어로 표현하면?', '가장 가까운 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (117, 30, '안정', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (118, 30, '확장', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (119, 30, '흐릿함', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (120, 30, '긴장', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (31, 'spending', 'saving', '🏦', '월급이나 용돈이 들어오면 가장 먼저 하는 일은?', '가장 자주 하는 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (121, 31, '저축/투자 금액부터 나눈다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (122, 31, '고정지출부터 체크한다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (123, 31, '사고 싶던 것을 찾아본다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (124, 31, '그날 기분에 따라 다르다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (32, 'spending', 'impulse', '🛍️', '세일 문구를 보면 보통 어떤 행동을 하나요?', '평소 소비 습관에 맞게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (125, 32, '바로 구매한다', 2, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (126, 32, '장바구니에 넣고 고민한다', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (127, 32, '필요한지 먼저 확인한다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (128, 32, '세일이어도 거의 관심 없다', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (33, 'spending', 'habit', '🍔', '배달앱을 열 때 가장 먼저 보는 것은?', '가장 자주 하는 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (129, 33, '최저주문/배달비', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (130, 33, '먹고 싶은 메뉴', 5, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (131, 33, '할인쿠폰 여부', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (132, 33, '리뷰 평점', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (34, 'spending', 'risk', '🎮', '한정판이나 인기 상품을 보면 어떤 편인가요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (133, 34, '지금 안 사면 후회할 것 같아 바로 산다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (134, 34, '필요하면 산다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (135, 34, '가격 추이를 지켜본다', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (136, 34, '대체품을 찾는다', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (35, 'spending', 'saving', '🧾', '가계부나 지출 메모는 어느 정도 하나요?', '실제 습관과 가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (137, 35, '거의 매일 기록한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (138, 35, '주기적으로 정리한다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (139, 35, '생각날 때만 적는다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (140, 35, '거의 하지 않는다', 2, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (36, 'spending', 'impulse', '📱', 'SNS에서 예쁜 제품을 보면 주로 어떻게 하나요?', '평소 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (141, 36, '링크를 눌러 바로 본다', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (142, 36, '저장해 두고 나중에 본다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (143, 36, '리뷰를 먼저 찾아본다', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (144, 36, '관심이 금방 사라진다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (37, 'spending', 'habit', '☕', '카페 이용 패턴은 어떤 편인가요?', '평소 지출 성향에 맞게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (145, 37, '습관적으로 자주 간다', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (146, 37, '필요할 때만 간다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (147, 37, '쿠폰/적립이 있을 때 간다', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (148, 37, '거의 가지 않는다', 10, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (38, 'spending', 'risk', '🎲', '새로운 재테크/구매 제안을 들으면 어떤 편인가요?', '가장 가까운 태도를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (149, 38, '일단 해본다', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (150, 38, '주변 후기를 본다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (151, 38, '수익/손실을 계산해 본다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (152, 38, '낯설면 피한다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (39, 'spending', 'saving', '🥡', '냉장고에 재료가 있을 때 외식을 제안받으면?', '가장 자주 하는 선택을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (153, 39, '외식한다', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (154, 39, '상황 보고 결정한다', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (155, 39, '집 재료를 먼저 활용한다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (156, 39, '할인 있으면 외식한다', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (40, 'spending', 'impulse', '👟', '신발이나 옷을 살 때 가장 큰 기준은?', '가장 공감되는 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (157, 40, '지금 갖고 싶은지', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (158, 40, '오래 입을 수 있는지', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (159, 40, '브랜드/유행', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (160, 40, '할인 폭', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (41, 'spending', 'habit', '🚕', '이동할 때 택시를 타는 기준은?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (161, 41, '귀찮으면 탄다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (162, 41, '시간이 촉박할 때만 탄다', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (163, 41, '비용보다 편함이 중요하다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (164, 41, '가능하면 대중교통을 탄다', 10, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (42, 'spending', 'risk', '🎁', '친구 선물 예산을 잡을 때 보통 어떤 편인가요?', '평소 방식에 맞게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (165, 42, '기분 따라 넉넉히 쓴다', 5, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (166, 42, '상대와 상황에 맞춰 정한다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (167, 42, '미리 예산선을 정한다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (168, 42, '행사/할인을 적극 활용한다', 9, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (43, 'spending', 'saving', '📦', '정기구독 서비스를 정리할 때 가장 가까운 패턴은?', '실제 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (169, 43, '매달 확인한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (170, 43, '분기별로 정리한다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (171, 43, '생각날 때만 본다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (172, 43, '거의 정리 안 한다', 2, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (44, 'spending', 'impulse', '🍰', '기분이 안 좋을 때 소비하는 편인가요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (173, 44, '자주 그렇다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (174, 44, '가끔 그렇다', 5, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (175, 44, '대체 활동을 찾는다', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (176, 44, '거의 없다', 10, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (45, 'spending', 'habit', '🏪', '편의점에 들렀을 때 가장 흔한 패턴은?', '가장 자주 하는 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (177, 45, '예정 없던 것도 함께 산다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (178, 45, '필요한 것만 산다', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (179, 45, '행사 상품을 먼저 본다', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (180, 45, '들어가도 안 사는 경우가 많다', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (46, 'spending', 'risk', '💄', '새로운 브랜드를 써볼 때 당신은?', '가장 가까운 태도를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (181, 46, '광고 보고 바로 산다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (182, 46, '샘플/후기를 본다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (183, 46, '검증된 것만 산다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (184, 46, '할인하면 시도한다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (47, 'spending', 'saving', '📚', '자기계발이나 취미에 돈을 쓸 때 기준은?', '실제 소비 판단 기준을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (185, 47, '성장 가능성이 있으면 쓴다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (186, 47, '가격이 적당하면 쓴다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (187, 47, '그때 끌리면 쓴다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (188, 47, '거의 안 쓴다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (48, 'spending', 'impulse', '🧋', '신메뉴/신제품이 나오면 어떤 편인가요?', '가장 가까운 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (189, 48, '바로 먹어본다/사본다', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (190, 48, '후기를 보고 결정한다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (191, 48, '쿠폰이 있으면 시도한다', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (192, 48, '굳이 안 해본다', 9, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (49, 'spending', 'habit', '💡', '전기/통신 같은 고정비는 얼마나 신경 쓰나요?', '평소 관리 수준을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (193, 49, '자주 점검하고 바꾼다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (194, 49, '필요할 때만 비교한다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (195, 49, '거의 신경 안 쓴다', 3, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (196, 49, '부모/가족이 관리한다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (50, 'spending', 'risk', '🎉', '친구들과 모임에서 예상보다 비용이 커지면?', '가장 가까운 반응을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (197, 50, '분위기 좋으면 신경 안 쓴다', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (198, 50, '다음 지출을 줄인다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (199, 50, '애초에 예산을 생각하며 움직인다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (200, 50, '계산할 때 스트레스가 크다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (51, 'spending', 'saving', '🪙', '잔돈이나 소액 포인트는 어떻게 하나요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (201, 51, '틈틈이 모은다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (202, 51, '생각날 때만 챙긴다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (203, 51, '거의 신경 안 쓴다', 3, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (204, 51, '소액이라 바로 써버린다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (52, 'spending', 'impulse', '📦', '무료배송 기준 금액이 조금 모자라면?', '가장 자주 하는 선택을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (205, 52, '아무거나 더 담는다', 2, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (206, 52, '정말 필요한 게 있는지 본다', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (207, 52, '배송비를 내는 편이다', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (208, 52, '다음에 사기로 미룬다', 9, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (53, 'spending', 'habit', '🍿', 'OTT나 게임 결제는 어떤 편인가요?', '실제 패턴에 맞게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (209, 53, '충동적으로 자주 결제한다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (210, 53, '즐길 가치가 있으면 결제한다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (211, 53, '정기적으로 한도 내에서 쓴다', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (212, 53, '거의 결제 안 한다', 10, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (54, 'spending', 'risk', '🧑‍🤝‍🧑', '주변 사람이 추천한 물건을 보면?', '가장 가까운 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (213, 54, '믿고 산다', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (214, 54, '후기와 가격을 함께 본다', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (215, 54, '내 필요가 맞아야 산다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (216, 54, '추천받아도 잘 안 산다', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (55, 'spending', 'saving', '💼', '큰돈이 들어가는 물건을 살 때 준비 과정은?', '평소 습관에 맞게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (217, 55, '바로 결정한다', 2, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (218, 55, '가격 비교를 충분히 한다', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (219, 55, '후기만 많이 본다', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (220, 55, '주변 의견을 먼저 듣는다', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (56, 'spending', 'impulse', '🍕', '배가 고프지 않은데 맛집 콘텐츠를 보면?', '가장 가까운 반응을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (221, 56, '주문부터 한다', 2, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (222, 56, '저장만 해둔다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (223, 56, '다음 일정과 예산을 보고 정한다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (224, 56, '금방 잊는다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (57, 'spending', 'habit', '🏷️', '할인 쿠폰은 어떻게 활용하나요?', '실제 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (225, 57, '있으면 무조건 쓴다', 5, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (226, 57, '필요한 소비에만 쓴다', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (227, 57, '모아두다 만료된다', 3, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (228, 57, '쿠폰 자체를 잘 안 본다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (58, 'spending', 'risk', '🧪', '가성비 제품과 프리미엄 제품 중 보통 어떤 쪽인가요?', '가장 가까운 소비 기준을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (229, 58, '무조건 싼 쪽', 6, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (230, 58, '상황에 따라 다르다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (231, 58, '오래 쓸 건 좋은 걸 산다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (232, 58, '비싸 보이면 더 끌린다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (59, 'spending', 'saving', '🏠', '집에서 먹을 수 있는데 밖에서 사 먹는 빈도는?', '실제 패턴을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (233, 59, '자주 그렇다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (234, 59, '주 1~2회 정도', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (235, 59, '일정한 선에서 조절한다', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (236, 59, '가능하면 집에서 해결한다', 10, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (60, 'spending', 'impulse', '🎀', '포장이나 디자인이 예쁘면 구매 확률이 올라가나요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (237, 60, '많이 올라간다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (238, 60, '조금 영향 있다', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (239, 60, '기능/가격이 더 중요하다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (240, 60, '후기 없으면 안 산다', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (61, 'spending', 'habit', '📆', '월별 예산을 미리 정하는 편인가요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (241, 61, '세부 항목까지 정한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (242, 61, '대략적으로만 잡는다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (243, 61, '생각은 하지만 잘 안 지킨다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (244, 61, '거의 정하지 않는다', 2, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (62, 'spending', 'risk', '🧳', '여행 준비 시 쇼핑 예산은 어떻게 잡나요?', '가장 가까운 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (245, 62, '현장에서 분위기 따라 쓴다', 4, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (246, 62, '대략 한도만 정한다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (247, 62, '항목별로 예산을 잡는다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (248, 62, '쇼핑은 최소화한다', 9, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (63, 'spending', 'saving', '📉', '이번 달 지출이 많았다고 느끼면 보통?', '평소 대처를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (249, 63, '다음 달 조정 계획을 세운다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (250, 63, '그냥 다음 달부터 조심한다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (251, 63, '왜 많았는지 잘 안 본다', 3, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (252, 63, '할인/쿠폰으로 만회하려 한다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (64, 'spending', 'impulse', '🎧', '전자기기 신제품 소식을 보면 어떤 편인가요?', '가장 가까운 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (253, 64, '예약부터 알아본다', 3, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (254, 64, '리뷰를 충분히 본다', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (255, 64, '지금 기기가 괜찮으면 넘긴다', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (256, 64, '할인 시기만 기다린다', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (65, 'spending', 'habit', '🧹', '집에 안 쓰는 물건이 많을 때 보통?', '실제 행동을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (257, 65, '중고 판매나 정리를 한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (258, 65, '그냥 둔다', 3, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (259, 65, '언젠가 쓸 거라 생각한다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (260, 65, '가끔 정리한다', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (66, 'future', 'investment', '📈', '5년 뒤 자산을 늘리기 위해 가장 중요한 것은 무엇이라고 생각하나요?', '직감적으로 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (261, 66, '꾸준한 저축 습관', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (262, 66, '공부한 뒤 하는 투자', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (263, 66, '큰 기회를 잡는 감각', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (264, 66, '수입을 늘리는 도전', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (67, 'future', 'goal', '🗺️', '미래 재무 목표를 떠올리면 가장 먼저 생각나는 것은?', '가장 가까운 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (265, 67, '내 집 마련', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (266, 67, '안정적인 비상금', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (267, 67, '여행과 경험', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (268, 67, '경제적 자유', 9, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (68, 'future', 'investment', '💹', '주식이나 펀드 같은 자산에 대해 당신의 태도는?', '현재 생각과 가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (269, 68, '공부해서 천천히 해보고 싶다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (270, 68, '이미 조금씩 실천 중이다', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (271, 68, '관심은 있지만 어렵다', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (272, 68, '변동성이 무서워 피하고 싶다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (69, 'future', 'goal', '🏡', '큰돈이 생기면 가장 우선하고 싶은 미래 계획은?', '가장 솔직한 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (273, 69, '안정 자산 확보', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (274, 69, '수익형 투자', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (275, 69, '삶의 질 향상', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (276, 69, '당장 하고 싶은 것 실현', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (70, 'future', 'risk', '🎢', '높은 수익 가능성과 안정성 중 더 끌리는 쪽은?', '가장 가까운 태도를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (277, 70, '안정성이 더 중요하다', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (278, 70, '조금 높은 수익이면 감수 가능', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (279, 70, '수익이 크면 위험도 감수', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (280, 70, '잘 모르겠다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (71, 'future', 'habit', '📚', '돈 공부를 위해 시간을 쓴다면 어떤 방식이 좋나요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (281, 71, '책/유튜브로 꾸준히 공부', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (282, 71, '짧은 콘텐츠로 핵심만 본다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (283, 71, '주변 사람에게 듣는다', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (284, 71, '공부보다 실전이 낫다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (72, 'future', 'income', '💼', '미래 자산을 위해 가장 먼저 키우고 싶은 것은?', '가장 중요한 요소를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (285, 72, '본업 수입', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (286, 72, '부수입 파이프라인', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (287, 72, '절약 습관', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (288, 72, '투자 감각', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (73, 'future', 'goal', '⏳', '장기 목표를 위해 소비를 미루는 것이 가능한 편인가요?', '평소 성향에 맞게 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (289, 73, '꽤 잘하는 편이다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (290, 73, '필요하면 할 수 있다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (291, 73, '가끔 어렵다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (292, 73, '당장 만족이 더 중요하다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (74, 'future', 'investment', '🏗️', '미래를 위한 돈은 어떤 곳에 쓰는 게 가장 가치 있다고 보나요?', '가장 공감되는 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (293, 74, '자기계발', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (294, 74, '안정 자산 형성', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (295, 74, '사업/사이드 프로젝트', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (296, 74, '네트워크와 경험', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (75, 'future', 'risk', '🌊', '시장이 흔들릴 때 당신의 예상 반응은?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (297, 75, '추가 공부 후 대응한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (298, 75, '일단 관망한다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (299, 75, '불안해서 바로 정리한다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (300, 75, '오히려 기회라고 본다', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (76, 'future', 'habit', '🧩', '미래 준비에서 당신이 가장 자신 있는 것은?', '가장 가까운 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (301, 76, '계획 세우기', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (302, 76, '실행력', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (303, 76, '기회 포착', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (304, 76, '절약 버티기', 8, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (77, 'future', 'income', '🧑‍💻', '부업이나 추가 수입 기회가 생기면 어떤 편인가요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (305, 77, '가능성을 먼저 계산한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (306, 77, '재미있으면 시도한다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (307, 77, '시간이 부족해 미룬다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (308, 77, '안정적이지 않으면 안 한다', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (78, 'future', 'goal', '🧱', '미래 자산의 ''기초 체력''이라고 느끼는 것은?', '가장 공감되는 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (309, 78, '비상금', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (310, 78, '지출 통제', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (311, 78, '꾸준한 수입', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (312, 78, '투자 경험', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (79, 'future', 'investment', '🪴', '소액으로라도 장기적으로 키우고 싶은 자산이 있나요?', '현재 생각과 가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (313, 79, '예적금/현금성 자산', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (314, 79, '주식/ETF', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (315, 79, '부동산 관련 자산', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (316, 79, '아직 잘 모르겠다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (80, 'future', 'risk', '🎯', '한 번의 큰 성공보다 꾸준한 성장이 더 중요하다고 보나요?', '가치관에 맞는 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (317, 80, '매우 그렇다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (318, 80, '대체로 그렇다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (319, 80, '상황에 따라 다르다', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (320, 80, '큰 한 방도 중요하다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (81, 'future', 'habit', '📅', '1년 뒤 금전 목표를 적어본 적이 있나요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (321, 81, '구체적으로 적어봤다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (322, 81, '대략 생각은 해봤다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (323, 81, '막연히만 있다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (324, 81, '거의 없다', 2, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (82, 'future', 'income', '🧠', '당신에게 돈을 더 벌 가능성이 높은 방식은 무엇 같나요?', '직감적으로 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (325, 82, '지금 하는 일의 전문성 강화', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (326, 82, '새로운 기술 습득', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (327, 82, '사업/판매 도전', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (328, 82, '투자 수익 확대', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (83, 'future', 'goal', '🔭', '10년 뒤 가장 원하는 재무 상태는?', '가장 바라는 모습을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (329, 83, '빚 없이 안정적인 생활', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (330, 83, '꾸준히 불어나는 자산', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (331, 83, '원할 때 쉬어도 되는 여유', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (332, 83, '하고 싶은 소비를 자유롭게 하는 것', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (84, 'future', 'investment', '🧮', '투자 전 숫자와 데이터를 보는 편인가요?', '가장 가까운 태도를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (333, 84, '꼼꼼히 보는 편이다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (334, 84, '핵심만 보는 편이다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (335, 84, '감이 더 중요하다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (336, 84, '잘 안 본다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (85, 'future', 'risk', '🚦', '새로운 기회 앞에서 당신은 보통?', '가장 가까운 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (337, 85, '충분히 분석한 뒤 움직인다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (338, 85, '작게 먼저 시도한다', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (339, 85, '기회 같으면 빠르게 간다', 7, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (340, 85, '망설이다 놓친다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (86, 'future', 'habit', '🪙', '미래를 위해 지금 당장 줄일 수 있는 소비가 있나요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (341, 86, '이미 알고 있고 줄이는 중이다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (342, 86, '생각은 있지만 아직 못 줄였다', 6, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (343, 86, '딱히 떠오르지 않는다', 4, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (344, 86, '줄이기보다 더 벌고 싶다', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (87, 'future', 'income', '🛠️', '실력을 돈으로 바꾸는 데 가장 필요한 것은?', '가장 중요하다고 느끼는 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (345, 87, '꾸준한 실행', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (346, 87, '홍보/노출', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (347, 87, '차별화된 아이디어', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (348, 87, '사람들과의 연결', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (88, 'future', 'goal', '🌱', '미래 자산을 떠올리면 지금 가장 먼저 해야 할 일은?', '가장 가까운 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (349, 88, '예산 정리', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (350, 88, '목표 금액 설정', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (351, 88, '수입 확대 계획', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (352, 88, '불필요한 소비 파악', 9, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (89, 'future', 'investment', '🧭', '경제 뉴스나 시장 흐름을 보는 이유가 있다면?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (353, 89, '기회를 놓치지 않기 위해', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (354, 89, '내 자산 판단을 위해', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (355, 89, '그냥 관심 있어서', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (356, 89, '거의 보지 않는다', 3, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (90, 'future', 'risk', '🧪', '새로운 투자 상품을 접하면 첫 반응은?', '가장 가까운 태도를 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (357, 90, '원리부터 이해하려 한다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (358, 90, '주변 후기부터 찾는다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (359, 90, '수익률만 먼저 본다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (360, 90, '복잡해 보여서 피한다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (91, 'future', 'habit', '📥', '미래 대비용 통장을 따로 두는 게 중요하다고 보나요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (361, 91, '매우 중요하다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (362, 91, '있으면 좋다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (363, 91, '한 통장으로도 충분하다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (364, 91, '잘 모르겠다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (92, 'future', 'income', '🚀', '당신의 미래 소득을 가장 크게 바꿀 수 있는 것은?', '가장 가능성 높은 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (365, 92, '직무 전문성', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (366, 92, 'AI/디지털 역량', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (367, 92, '사람과의 협업 기회', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (368, 92, '투자 감각', 7, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (93, 'future', 'goal', '🎓', '배움에 돈을 쓰는 것을 어떻게 보나요?', '가장 가까운 가치관을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (369, 93, '장기적으로 가장 좋은 투자다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (370, 93, '필요한 경우에만 한다', 7, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (371, 93, '비용 대비 효과를 많이 따진다', 8, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (372, 93, '당장 체감이 적어 망설여진다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (94, 'future', 'investment', '🏘️', '부동산, 금융자산, 현금 중 하나를 먼저 키운다면?', '지금 생각과 가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (373, 94, '현금/비상금', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (374, 94, '금융자산', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (375, 94, '실물/부동산 기반 자산', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (376, 94, '아직 판단이 어렵다', 5, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (95, 'future', 'risk', '⚖️', '리스크를 줄이는 가장 좋은 방법은 무엇이라 생각하나요?', '가장 공감되는 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (377, 95, '분산', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (378, 95, '무리하지 않는 규모', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (379, 95, '공부와 정보', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (380, 95, '타이밍', 6, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (96, 'future', 'habit', '🧺', '작은 루틴이 미래 자산을 만든다고 느끼나요?', '가장 가까운 생각을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (381, 96, '아주 크게 느낀다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (382, 96, '어느 정도 그렇다', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (383, 96, '크게 체감은 없다', 5, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (384, 96, '잘 모르겠다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (97, 'future', 'income', '📣', '내가 가진 것을 더 잘 알리면 수입이 늘 수 있다고 보나요?', '가장 가까운 답을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (385, 97, '그렇다, 브랜딩이 중요하다', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (386, 97, '실력과 함께 중요하다', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (387, 97, '알지만 실행이 어렵다', 6, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (388, 97, '별로 관계없다', 4, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (98, 'future', 'goal', '🏁', '미래 자산 목표에 가까워졌다고 느끼는 순간은?', '가장 공감되는 항목을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (389, 98, '지출 통제가 익숙해졌을 때', 8, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (390, 98, '자산이 자동으로 쌓이는 구조가 생겼을 때', 10, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (391, 98, '수입원이 늘어났을 때', 9, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (392, 98, '큰 지출에도 흔들리지 않을 때', 10, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (99, 'future', 'investment', '📊', '장기적으로 돈이 모이는 사람의 특징은 무엇 같나요?', '가장 가까운 생각을 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (393, 99, '꾸준한 기록', 9, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (394, 99, '기회가 왔을 때 실행', 8, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (395, 99, '감정 조절', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (396, 99, '목표의식', 9, 4);
INSERT INTO questions (id, test_type, category, emoji, question_text, question_subtext, is_active, weight, created_at) VALUES (100, 'future', 'habit', '🔐', '미래 자산을 위해 지금 가장 먼저 지켜야 할 원칙 하나는?', '직감적으로 골라주세요.', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (397, 100, '수입보다 적게 쓰기', 10, 1);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (398, 100, '꾸준히 모으기', 9, 2);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (399, 100, '모르는 것은 공부하고 투자하기', 10, 3);
INSERT INTO choices (id, question_id, choice_text, score, choice_order) VALUES (400, 100, '남과 비교하지 않기', 8, 4);
COMMIT;
